service: aws-lambda-warmup

plugins:
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  memorySize: 128
  timeout: 3
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    warmup:
      enabled: true
      concurrency: 5
      prewarm: true
